### ISSUE TITLE
Possible incompatibility with Astro 4.10.2 - Invalid images

### ISSUE THREAD

**Issue by julien-deramond** [delucis/astro-og-canvas#61] opened 2024-07-01 21:38 UTC
Hello there!
Thanks a lot for this package 🙏 

### Description

From my initial analysis, it seems there may be an issue when using Astro OG Canvas with Astro version 4.10.2 and above.

Based on my understanding, Astro OG Canvas should be compatible since its peer dependency is specified as `"astro": "^3.0.0 || ^4.0.0"`.

However, images built from Astro version 4.10.2 onwards appear to be invalid in my environment:
- They cannot be opened with a regular image preview tool.
- Their size is significantly smaller (e.g., from 61K to 14K); probably due to the fact they are invalid.

![Screenshot 2024-07-01 at 23 21 44](https://github.com/delucis/astro-og-canvas/assets/17381666/0d01c327-4391-40e3-880a-b60fefdf320e)

### Reproducible environment

To reproduce the issue with my current environment, please follow these steps:

```bash
cd /tmp
git clone git@github.com:Open-reSource/openresource.dev.git
cd openresource.dev
npm i
npm run build

# Open for instance .vercel/output/static/open-graph/articles/can-i-take-this-issue.png 
# It's going to be invalid
```

This build uses Astro 4.11.3.

### Digging into the Past

The error starts to occur from this commit: https://github.com/Open-reSource/openresource.dev/commit/b96782ad65aba543738aed5fc4b3d7a9d9fea8b9

Notably, the code related to Astro OG Canvas hasn't changed for a long time and can be found here: https://github.com/Open-reSource/openresource.dev/blob/main/src/pages/open-graph/%5B...path%5D.ts. It worked previously and appears correct according to the documentation.

Using the reproducible environment, you can verify the issue:

```bash
git checkout b96782ad65aba543738aed5fc4b3d7a9d9fea8b9
# You can force in "package.json" the version of Astro to be strictly 4.10.2 just to be sure
npm i
npm run build
```

The issue persists, as expected.

Now, if you change `"astro": "^4.10.2"` to `"astro": "4.10.1"` in the `package.json` and then run `npm i; npm run build`, you'll find that the image at `.vercel/output/static/open-graph/articles/can-i-take-this-issue.png` is now valid.

<img src="https://github.com/delucis/astro-og-canvas/assets/17381666/b83afe7e-7425-44ba-84f1-9033f68223e4" width="300">

This is what makes me think there's an incompatibility starting from Astro 4.10.2 precisely.

### Next steps?

It seems there's an incompatibility between Astro OG Canvas and Astro version 4.10.2 (and later versions).

My knowledge is limited in diagnosing the root cause further 😬 
I can try, but I'll maybe need some guidance to where to look at.
If you need additional actions or tests to gather more precise information on my side, please let me know, and I'll follow your guidance 🙏

**Comment by delucis** [comment] 2024-07-01 22:28
Thanks for the thorough report @julien-deramond! It does indeed sound like something changed in that specific Astro version based on your description.

It seems to only a problem in build as far as I can tell — during dev the images get served correctly.

I’m looking at the [Astro Changelog for 4.10.2](https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md#4102) to see if something obvious could be the cause, but I’m not quite sure 🤔

**Comment by delucis** [comment] 2024-07-01 22:30
Another weird details is that Astro Docs is on 4.11.0 and it is working, e.g. https://docs.astro.build/open-graph/en/getting-started.webp

Wondering if it’s something specific about the fact we are using WebP output instead of PNG.

**Comment by delucis** [comment] 2024-07-01 22:47
Hmm, actually, I take it back — I wasn’t able to reproduce in a fresh project where the PNGs were generated as expected.

~~@julien-deramond Could you try clearing the build cache for OG images in case it is this that is causing issues?~~

~~Deleting `node_modules/.astro-og-canvas` should force a full rebuild just in case you got into some bad state for some reason.~~

**Edit:** I tried your repo myself and can also see this behaviour. Thought it could be the Vercel adapter, but tried adding that to a fresh project and everything works fine there…

**Comment by delucis** [comment] 2024-07-01 23:15
Need to stop debugging for now, but can confirm:

- `npm run build` in https://github.com/Open-reSource/openresource.dev fails to generate the images correctly in `.vercel/static/open-graph/`.
- Pinning Astro to v4.10.1 or below fixes the issue.

Observations:

- It appears that the open graph endpoint is not ever called. Seems that Astro uses `getStaticPaths()` but then just writes the files without calling the `GET` handler.
- I tried to reproduce the bug in a small starter project but couldn’t even after adding the Vercel adapter and enabling SSR, so I’m not 100% sure what is the combination of circumstances required to trigger the bug.

**Comment by julien-deramond** [comment] 2024-07-02 04:34
Thanks a lot @delucis for your time and the analysis!

> Observations:
> * It appears that the open graph endpoint is not ever called. Seems that Astro uses `getStaticPaths()` but then just writes the files without calling the GET handler.
> * I tried to reproduce the bug in a small starter project but couldn’t even after adding the Vercel adapter and enabling SSR, so I’m not 100% sure what is the combination of circumstances required to trigger the bug.

I'll try from these statements to replicate the issue today in a smaller starter project to try to find the combination of circumstances 🧐

**Comment by julien-deramond** [comment] 2024-07-02 10:19
_Sorry, I'll do it step-by-step depending on the amount of time I can find._

I've started a smaller project using `astro` (latest) and `astro-og-canvas` (latest): https://stackblitz.com/edit/github-9qfgh4?file=README.md
* When using the StackBlitz runner (or running it locally with `npm run dev`), the `og2` part is not working. Although the log shows that the pages' URLs are known and correct, the `GET` handler doesn't seem to be called.
* However, when this same project is run locally with `npm run build`, the `dist/og2/articles/week-1.png` file is correctly generated and valid.

This indicates that there is a different behavior when generating the images from `/src/pages` and `/src/content`.

However, this behavior is not new. I've tried running this exact same project with Astro version 3.x and older versions of astro-og-canvas, and the result is the same.

**Comment by julien-deramond** [comment] 2024-07-02 15:12
Starting from the project shared in https://github.com/delucis/astro-og-canvas/issues/61#issuecomment-2202660127, I've created a second project at https://stackblitz.com/edit/github-9qfgh4-aybz4g?file=package.json.

Let's add only `"@astrojs/vercel": "latest"` to the `package.json`:

```diff
  "dependencies": {
+    "@astrojs/vercel": "latest",
    "astro": "latest",
    "astro-og-canvas": "latest"
  }
```

Then, in `astro.config.mjs`:

```diff
export default defineConfig({
+  output: 'server',
+  adapter: vercel(),
});
```

Then, I've just added in the following files a `export const prerender = true;`:
* `src/pages/articles/[...slug].astro`
* `src/pages/og/[...route].astro`
* `src/pages/og2/[...path].astro`

When you download the project:

```sh
npm i
npm run build
```

- 🟢  `.vercel/output/static/og/test/test.png`
- 🟢  `.vercel/output/static/og/index.png`
- 🔴 `.vercel/output/static/og2/articles/week-1.png` (generated but not valid)

_(Only 2 images are generated in `node_modules/.astro-og-canvas`)_

Now, if you do:

```diff
  "dependencies": {
-    "@astrojs/vercel": "latest",
+    "@astrojs/vercel": "^6",
-    "astro": "latest",
+    "astro": "4.10.1",
    "astro-og-canvas": "latest"
  }
```

- 🟢  `.vercel/output/static/og/test/test.png`
- 🟢  `.vercel/output/static/og/index.png`
- 🟢  `.vercel/output/static/og2/articles/week-1.png`

_(3 images are generated in `node_modules/.astro-og-canvas`)_

Final test:

```diff
  "dependencies": {
      "@astrojs/vercel": "^6",
-    "astro": "4.10.1",
+    "astro": "4.10.2",
    "astro-og-canvas": "latest"
  }
```

- 🟢  `.vercel/output/static/og/test/test.png`
- 🟢  `.vercel/output/static/og/index.png`
- 🔴 `.vercel/output/static/og2/articles/week-1.png` (generated but not valid)

_(Only 2 images are generated in `node_modules/.astro-og-canvas`)_

Note: I still don't know why there's something wrong from Astro v4.10.2, but the project is more minimal and reproducible compared to my GitHub real repository. Hope it can help with our further investigations 🙌

**Comment by delucis** [comment] 2024-07-02 15:23
Oh, one interesting thing to me is that the one that is breaking has numbers in the path. Could you test if that’s the issue? I also recall you mentioning something like a `111111.png` previously.

**Comment by julien-deramond** [comment] 2024-07-02 15:27
> Oh, one interesting thing to me is that the one that is breaking has numbers in the path. Could you test if that’s the issue? I also recall you mentioning something like a `111111.png` previously.

Renamed `week-1.md` to `week.md`, the `.vercel/output/static/og2/articles/week.png` is broken too.

**Comment by delucis** [comment] 2024-07-02 15:27
> Renamed `week-1.md` to `week.md`, the `.vercel/output/static/og2/articles/week.png` is broken too.

And if `og2` is `og-two` or something like that?

**Comment by julien-deramond** [comment] 2024-07-02 15:29
> And if `og2` is `og-two` or something like that?

Same thing, `.vercel/output/static/ogtwo/articles/week.png` is broken too. And only 2 images are generated in `node_modules/.astro-og-canvas`.

**Comment by delucis** [comment] 2024-07-02 15:34
OK, thanks. Worth a shot! Will try to take a look at the reduced reproduction in a bit. I’m guessing it’s an Astro bug, but the tricky bit is narrowing down what exactly changed.

**Comment by julien-deramond** [comment] 2024-07-05 13:02
I've recompiled Astro at different steps [between 4.10.1 and 4.10.2](https://github.com/withastro/astro/compare/astro%404.10.1...astro%404.10.2) and used it in the same context as [my reproducible env](https://stackblitz.com/edit/github-9qfgh4-aybz4g?file=package.json). If I'm not mistaken:
* Until https://github.com/withastro/astro/commit/416c4ac66d432d4c5abd13a4c7ecd20defb4fc30, the image is well generated
* From https://github.com/withastro/astro/commit/7327c6acb197e1f2ea6cf94cfbc5700bc755f982, the image is invalid

Some logs when it doesn't work:

```
15:07:46 λ src/pages/og2/[...path].ts
params.ts - old: "/og2/articles/week-1.png"
params.ts - now: /og2/articles/week-1.png
generates.ts - old: /og2//articles/week-1.png
params.ts - old: "/og2/articles/week-1.png"
params.ts - now: /og2/articles/week-1.png
generates.ts - now: /og2/articles/week-1.png
params.ts - old: "/og2/articles/week-1.png"
params.ts - now: /og2/articles/week-1.png
15:07:46   └─ /og2/articles/week-1.pngparams.ts - old: "/og2/articles/week-1.png"
params.ts - now: /og2/articles/week-1.png
```

If I revert this part only in `packages/astro/src/core/build/generate.ts`, the image is well generated:

```diff
+ return route.generate(staticPath.params);
- return stringifyParams(staticPath.params, route);
```

I just tried to use the values from the log:

```
return '/og2//articles/week-1.png' // works
return '/og2/articles/week-1.png' // does not work
```

The returned value of `getPathsForRoute` function:
* when it works: `paths` is equal to `[ '/og2//articles/week-1.png' ]`
* when it doesn't work: `paths` is equal to `[ '/og2/articles/week-1.png' ]`

Let's maybe continue digging from there, even if it's starting to be a lil' bit too deep into the framework for me 😁

**Comment by delucis** [comment] 2024-07-05 14:48
Innnnnteresting! Great work bisecting that.

The actual issue is that the change in https://github.com/withastro/astro/pull/10607 means that the `param` an endpoint is called with can be different from the `param` that was set in `getStaticPaths`, for example:

```js
export function getStaticPaths() {
  return [{ params: { a: '/foo/' } }];
}

export function GET({ params }) {
  console.log(params.a);
  // Logs 'foo/', not '/foo/'
}
```

In `astro-og-canvas` we relied on getting the param back untouched to look up the entry to use for rendering, and this change broke that assumption. We were hitting this line for params starting with a leading slash:

https://github.com/delucis/astro-og-canvas/blob/c552589be3757bfe06cd598d27644a73dede5010/packages/astro-og-canvas/src/routing.ts#L29

I think we should be able to patch this in `astro-og-canvas` as a hotfix although I’m not sure if this change is technically a bug on Astro’s end — at the very least it’s a behaviour change some people might have been depending on.

**Comment by delucis** [comment] 2024-07-05 16:04
Are you interested in PR’ing a fix for this @julien-deramond?

I think probably the most solid approach for now would be to update this lookup:

https://github.com/delucis/astro-og-canvas/blob/c552589be3757bfe06cd598d27644a73dede5010/packages/astro-og-canvas/src/routing.ts#L26-L28

We should probably check for both the slug and the slug without the leading slash there.

**Closed as completed** 2024-07-06 10:25 UTC
